# Generated by Django 3.1.7 on 2021-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField()),
                ('location', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='static/%y')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
